# Generated by Django 5.2.8 on 2025-11-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='id of an event')),
                ('start_date', models.DateTimeField(verbose_name='starting date and time of an event')),
                ('end_date', models.DateTimeField(verbose_name='ending date and time of an event')),
                ('name', models.TextField(verbose_name='name of an event')),
                ('decsription', models.TextField(verbose_name='description of an event')),
                ('category', models.TextField(verbose_name='category of an event')),
            ],
        ),
    ]
